stages:
  - build

variables:
  DEBIAN_FRONTEND: "noninteractive"
  # At https://salsa.debian.org/salsa-ci-team/pipeline/container_registry one can see which images are available
  SALSA_CI_IMAGES: registry.salsa.debian.org/salsa-ci-team/pipeline
  BASE_CI_IMAGES: ${SALSA_CI_IMAGES}/base

build-yamls:
  stage: build
  image: $BASE_CI_IMAGES:unstable
  dependencies: []
  script:
    - apt-get update && eatmydata apt-get install -y vmdb2 dosfstools qemu-utils qemu-user-static debootstrap binfmt-support time kpartx bmap-tools python3 fakemachine make
    - make yaml
    - mkdir build
    - cp raspi*.yaml build
  artifacts:
    paths:
      - build

